'use strict';

var gulp = require('gulp');
var plugins = require('gulp-load-plugins')();
var rimraf = require('rimraf');
var browserSync = require('browser-sync');
var runSequence = require('run-sequence');
var karma = require('karma').server;
var historyApiFallback = require('connect-history-api-fallback');

// DEVELOPMENT TASKS
//================================================

/*
* 1. Setup a webserver with livereload using BrowserSync
* 2. JS and CSS get processed and served from the 'build' folder
* 3. JSX: Transform jsx React files and put in build 'build' folder
* 4. Compile sass files, autoprefix and put in 'build' folder
* */

 // BrowserSync Server
gulp.task('browser-sync', function() {
  browserSync.init([
    './build/css/*.css',
    './build/js/**/*.js',
    './**/*.html'
  ],
  {
    notify: false,
    server: {
      baseDir: ['./'],
      middleware:[historyApiFallback] //https://github.com/BrowserSync/browser-sync/issues/204#issuecomment-60410751
    },
    port: 3500,
    browser: [],
    tunnel: false
  });
});

// JSX
gulp.task('jsx', function() {
  return gulp.src('src/scripts/**/*.js')
    .pipe(plugins.cached('jsx'))  //Process only changed files
    .pipe(plugins.react())
    .on('error', plugins.util.log)
    .pipe(gulp.dest('build/js'));
});

// Sass
gulp.task('sass', function() {
  return gulp.src('./src/styles/main.scss')
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.sass())
    .pipe(plugins.sourcemaps.write({includeContent: false}))
    .pipe(plugins.sourcemaps.init({loadMaps: true})) // Load sourcemaps generated by sass
    .pipe(plugins.autoprefixer({
      browsers: ['last 2 versions']
    }))
    .on('error', plugins.util.log)
    .pipe(plugins.sourcemaps.write())
    .pipe(gulp.dest('./build/css'))
    .on('error', plugins.util.log);
});

// Assets
gulp.task('assets', function () {
  return gulp.src('./src/assets/**/*.*')
      .pipe(gulp.dest('./build/assets'))
      .on('error', plugins.util.log);
});

// serve task
gulp.task('serve', ['browser-sync', 'jsx', 'sass', 'assets'] , function(cb) {

  plugins.watch(
    './src/styles/**/*.scss',
    {
      name: 'SASS'
    },
    function() {
      runSequence('sass');
    }
  );

  plugins.watch(
    './src/scripts/**/*.js',
    {
      name: 'JS'
    },
    function() {
      // notes on gulp.start: http://stackoverflow.com/questions/21905875/gulp-run-is-deprecated-how-do-i-compose-tasks
      gulp.start('jsx');
    }
  );

  plugins.watch(
    ['./docs/style_guide/**/*.*', '!./docs/style_guide/out/**/*.*'],
    {
      name: 'STYLE_GUIDE'
    },
    function() {
      gulp.start('style-guide');
    }
  );
});

// Delete build Directory
gulp.task('delete-build', function(cb) {
  rimraf('./build', cb);
});

//build (no server)
gulp.task('build', ['jsx', 'sass']);

// Default
gulp.task('default', runSequence.call(null, 'delete-build', 'serve'));

// Tests
gulp.task('test', function(done) {
  karma.start({
    configFile: __dirname + '/karma.conf.js'
  }, done);
});


// DISTRIBUTION TASKS
//===============================================

// Delete dist Directory
gulp.task('delete-dist', function() {
  rimraf('./dist', function(err) {
    plugins.util.log(err);
  });
});

// CSS
gulp.task('css', function() {
  return gulp.src('./build/css/main.css')
    .pipe(gulp.dest('./dist/css'))
    .pipe(plugins.csso())
    .pipe(plugins.rename('main.min.css'))
    .pipe(gulp.dest('./dist/css'))
    .on('error', plugins.util.log);
});

// Copy index.html to 'dist'
gulp.task('html', function() {
  gulp.src(['./index.html'])
    .pipe(gulp.dest('./dist'))
    .on('error', plugins.util.log);
});

// Bundle with jspm
gulp.task('bundle', ['jsx'], plugins.shell.task([
  'jspm bundle-sfx build/js/main dist/js/app.js'
]));

// Uglify the bundle
gulp.task('uglify', function() {
  return gulp.src('./dist/js/app.js')
    .pipe(plugins.sourcemaps.init({loadMaps: true}))
    .pipe(plugins.uglify())
    .pipe(plugins.sourcemaps.write('.'))
    .pipe(plugins.rename('app.min.js'))
    .pipe(gulp.dest('./dist/js'))
    .on('error', plugins.util.log);
});

gulp.task('dist', function() {
  runSequence(
    'delete-dist',
    'build',
    ['css', 'html', 'bundle'],
    'uglify'
  );
});

// DOCS TASKS
//===============================================

// Install rvm and then install hologram into the global rvm gemset. Bundler will find it.
gulp.task('style-guide', ['style-guide:sass'], function () {
  // Delete dir first because hologram has a bug where it'll keep nesting its outputs.
  rimraf('./docs/style_guide/out', function(err) {
    plugins.util.log(err);
  });

  return gulp.src('hologram_config.yml')
    .pipe(plugins.hologram({bundler: true, logging: true}))
    .on('error', plugins.util.log)
});

gulp.task('style-guide:sass', function () {
  return gulp.src('./docs/style_guide/src/styles/main.scss')
    .pipe(plugins.sourcemaps.init())
    .on('error', plugins.util.log)
    .pipe(plugins.sass())
    .pipe(plugins.sourcemaps.write())
    .pipe(gulp.dest('./docs/style_guide/doc_assets/static/css'))
});
