export const LOGIN_SUCCESS          = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS         = 'LOGOUT_SUCCESS';
export const RESUME_SESSION_SUCCESS = 'RESUME_SESSION_SUCCESS';
export const RESUME_SESSION_FAILURE = 'RESUME_SESSION_FAILURE';
