export const LOGIN_SUCCESS          = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS         = 'LOGOUT_SUCCESS';
export const RESUME_SESSION_SUCCESS = 'RESUME_SESSION_SUCCESS';
export const RESUME_SESSION_FAILURE = 'RESUME_SESSION_FAILURE';

export const USER_AGREEMENTS_RECEIVED = 'USER_AGREEMENTS_RECEIVED';

export const AGREEMENT_EDIT_REQUESTED = 'AGREEMENT_EDIT_REQUESTED';
export const AGREEMENT_EDIT_RECEIVED  = 'AGREEMENT_EDIT_RECEIVED';
export const EDIT_AGREEMENT_SUCCESS   = 'EDIT_AGREEMENT_SUCCESS';
export const EDIT_AGREEMENT_FAILURE   = 'EDIT_AGREEMENT_FAILURE';

export const AGREEMENT_DETAIL_REQUESTED = 'AGREEMENT_DETAIL_REQUESTED';
export const AGREEMENT_DETAIL_RECEIVED  = 'AGREEMENT_DETAIL_RECEIVED';
export const DETAIL_AGREEMENT_SUCCESS   = 'DETAIL_AGREEMENT_SUCCESS';
export const DETAIL_AGREEMENT_FAILURE   = 'DETAIL_AGREEMENT_FAILURE';

export const USER_AGREEMENT_TYPES_RECEIVED = 'USER_AGREEMENT_TYPES_RECEIVED';

export const USER_COUNTERPARTIES_RECEIVED = 'USER_COUNTERPARTIES_RECEIVED';

export const ADVANCED_SEARCH_RESET_PARAMETERS   = 'ADVANCED_SEARCH_RESET_PARAMETERS';
export const ADVANCED_SEARCH_SPECIFY_PARAMETERS = 'ADVANCED_SEARCH_SPECIFY_PARAMETERS';
export const ADVANCED_SEARCH_QUERY_REQUESTED    = 'ADVANCED_SEARCH_QUERY_REQUESTED';
export const ADVANCED_SEARCH_RESULTS_RECEIVED   = 'ADVANCED_SEARCH_RESULTS_RECEIVED';
export const ADVANCED_SEARCH_QUERY_FAILURE      = 'ADVANCED_SEARCH_QUERY_FAILURE';
