export const LOGIN_SUCCESS          = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS         = 'LOGOUT_SUCCESS';
export const RESUME_SESSION_SUCCESS = 'RESUME_SESSION_SUCCESS';
export const RESUME_SESSION_FAILURE = 'RESUME_SESSION_FAILURE';

export const USER_AGREEMENTS_RECEIVED = 'USER_AGREEMENTS_RECEIVED';

export const AGREEMENT_EDIT_REQUESTED              = 'AGREEMENT_EDIT_REQUESTED';
export const AGREEMENT_EDIT_RECEIVED               = 'AGREEMENT_EDIT_RECEIVED';
export const AGREEMENT_EDIT_SPECIFY_AGREEMENT_TYPE = 'AGREEMENT_EDIT_SPECIFY_AGREEMENT_TYPE';

export const AGREEMENT_SAVE_SUCCESS = 'AGREEMENT_SAVE_SUCCESS';
export const AGREEMENT_SAVE_FAILURE = 'AGREEMENT_SAVE_FAILURE';

export const AGREEMENT_DETAIL_REQUESTED = 'AGREEMENT_DETAIL_REQUESTED';
export const AGREEMENT_DETAIL_RECEIVED  = 'AGREEMENT_DETAIL_RECEIVED';
export const DETAIL_AGREEMENT_SUCCESS   = 'DETAIL_AGREEMENT_SUCCESS';
export const DETAIL_AGREEMENT_FAILURE   = 'DETAIL_AGREEMENT_FAILURE';

export const USER_AGREEMENT_TYPES_RECEIVED = 'USER_AGREEMENT_TYPES_RECEIVED';

export const AGREEMENT_TYPE_SAVE_SUCCESS = 'AGREEMENT_TYPE_SAVE_SUCCESS';
export const AGREEMENT_TYPE_SAVE_FAILURE = 'AGREEMENT_TYPE_SAVE_FAILURE';

export const USER_COUNTERPARTIES_RECEIVED = 'USER_COUNTERPARTIES_RECEIVED';

export const ADVANCED_SEARCH_RESET_PARAMETERS   = 'ADVANCED_SEARCH_RESET_PARAMETERS';
export const ADVANCED_SEARCH_SPECIFY_PARAMETERS = 'ADVANCED_SEARCH_SPECIFY_PARAMETERS';
export const ADVANCED_SEARCH_QUERY_REQUESTED    = 'ADVANCED_SEARCH_QUERY_REQUESTED';
export const ADVANCED_SEARCH_RESULTS_RECEIVED   = 'ADVANCED_SEARCH_RESULTS_RECEIVED';
export const ADVANCED_SEARCH_QUERY_FAILURE      = 'ADVANCED_SEARCH_QUERY_FAILURE';

export const USER_SMART_VIEWS_RECEIVED = 'USER_SMART_VIEWS_RECEIVED';
export const SMART_VIEW_SAVE_SUCCESS   = 'SMART_VIEW_SAVE_SUCCESS';
export const SMART_VIEW_SAVE_FAILURE   = 'SMART_VIEW_SAVE_FAILURE';
export const SMART_VIEW_EDIT_SELECTED  = 'SMART_VIEW_EDIT_SELECTED';
export const SMART_VIEW_EDIT_CLEAR     = 'SMART_VIEW_EDIT_CLEAR';

export const USER_ALERTS_RECEIVED = 'USER_ALERTS_RECEIVED';
