// Redux Messaging
export const LOGIN_SUCCESS          = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS         = 'LOGOUT_SUCCESS';
export const RESUME_SESSION_SUCCESS = 'RESUME_SESSION_SUCCESS';
export const RESUME_SESSION_FAILURE = 'RESUME_SESSION_FAILURE';

export const USER_AGREEMENTS_RECEIVED = 'USER_AGREEMENTS_RECEIVED';

export const AGREEMENT_EDIT_REQUESTED = 'AGREEMENT_EDIT_REQUESTED';
export const AGREEMENT_EDIT_RECEIVED  = 'AGREEMENT_EDIT_RECEIVED';

export const AGREEMENT_SAVE_SUCCESS = 'AGREEMENT_SAVE_SUCCESS';
export const AGREEMENT_SAVE_FAILURE = 'AGREEMENT_SAVE_FAILURE';

export const AGREEMENT_DELETE_SUCCESS = 'AGREEMENT_DELETE_SUCCESS';
export const AGREEMENT_DELETE_FAILURE = 'AGREEMENT_DELETE_FAILURE';

export const ARTIFACT_DELETE_SUCCESS = 'ARTIFACT_DELETE_SUCCESS';
export const ARTIFACT_DELETE_FAILURE = 'ARTIFACT_DELETE_FAILURE';

export const AGREEMENT_DETAIL_REQUESTED = 'AGREEMENT_DETAIL_REQUESTED';
export const AGREEMENT_DETAIL_RECEIVED  = 'AGREEMENT_DETAIL_RECEIVED';
export const DETAIL_AGREEMENT_SUCCESS   = 'DETAIL_AGREEMENT_SUCCESS';
export const DETAIL_AGREEMENT_FAILURE   = 'DETAIL_AGREEMENT_FAILURE';

export const USER_AGREEMENT_TYPES_RECEIVED = 'USER_AGREEMENT_TYPES_RECEIVED';

export const USER_COUNTERPARTIES_RECEIVED = 'USER_COUNTERPARTIES_RECEIVED';

export const ADVANCED_SEARCH_RESET_PARAMETERS   = 'ADVANCED_SEARCH_RESET_PARAMETERS';
export const ADVANCED_SEARCH_SPECIFY_PARAMETERS = 'ADVANCED_SEARCH_SPECIFY_PARAMETERS';
export const ADVANCED_SEARCH_QUERY_REQUESTED    = 'ADVANCED_SEARCH_QUERY_REQUESTED';
export const ADVANCED_SEARCH_RESULTS_RECEIVED   = 'ADVANCED_SEARCH_RESULTS_RECEIVED';
export const ADVANCED_SEARCH_QUERY_FAILURE      = 'ADVANCED_SEARCH_QUERY_FAILURE';

export const USER_SMART_VIEWS_RECEIVED = 'USER_SMART_VIEWS_RECEIVED';
export const SMART_VIEW_SAVE_SUCCESS   = 'SMART_VIEW_SAVE_SUCCESS';
export const SMART_VIEW_SAVE_FAILURE   = 'SMART_VIEW_SAVE_FAILURE';
export const SMART_VIEW_EDIT_SELECTED  = 'SMART_VIEW_EDIT_SELECTED';
export const SMART_VIEW_EDIT_CLEAR     = 'SMART_VIEW_EDIT_CLEAR';

export const USER_ALERTS_RECEIVED = 'USER_ALERTS_RECEIVED';

export const USER_INFO_RECEIVED     = 'USER_INFO_RECEIVED';
export const USER_SUBSCRIBE_SUCCESS = 'USER_SUBSCRIBE_SUCCESS';
export const USER_SUBSCRIBE_FAILURE = 'USER_SUBSCRIBE_FAILURE';

// IoC
export const APP_STORE        = 'APP_STORE';
export const APP_STORE_CONFIG = 'APP_STORE_CONFIG';
export const ERROR_LOGGER     = 'ERROR_LOGGER';
export const LOG_LEVEL        = 'LOG_LEVEL';

export const SESSION_ACTIONS    = 'SESSION_ACTIONS';
export const SESSION_SERVICE    = 'SESSION_SERVICE';
export const SESSION_REPOSITORY = 'SESSION_REPOSITORY';

export const CLIENT_SIDE_PERSISTENCE_SERVICE = 'CLIENT_SIDE_PERSISTENCE_SERVICE';

export const LOGIN_COMPONENT = 'LOGIN_COMPONENT';
export const AUTH_SERVICE    = 'AUTH_SERVICE';

export const APP_LAYOUT_COMPONENT = 'APP_LAYOUT_COMPONENT';

export const SIDEBAR_COMPONENT = 'SIDEBAR_COMPONENT';

export const FOOTER_COMPONENT = 'FOOTER_COMPONENT';

export const HEADER_COMPONENT             = 'HEADER_COMPONENT';
export const HEADER_NAV_SECTION_COMPONENT = 'HEADER_NAV_SECTION_COMPONENT';
export const HEADER_SEARCH_COMPONENT      = 'HEADER_SEARCH_COMPONENT';

export const SEARCH_ACTIONS    = 'SEARCH_ACTIONS';
export const SEARCH_SERVICE    = 'SEARCH_SERVICE';
export const SEARCH_REPOSITORY = 'SEARCH_REPOSITORY';

export const SIMPLE_SEARCH_QUERY_LIST        = 'SIMPLE_SEARCH_QUERY_LIST';
export const SIMPLE_SEARCH_QUERY_LIST_ITEM   = 'SIMPLE_SEARCH_QUERY_LIST_ITEM';
export const SIMPLE_SEARCH_QUERY_INPUT_BOX   = 'SIMPLE_SEARCH_QUERY_INPUT_BOX';
export const ADVANCED_SEARCH_QUERY_CONTAINER = 'ADVANCED_SEARCH_QUERY_CONTAINER';

export const SMART_VIEW_ACTIONS    = 'SMART_VIEW_ACTIONS';
export const SMART_VIEW_SERVICE    = 'SMART_VIEW_SERVICE';
export const SMART_VIEW_REPOSITORY = 'SMART_VIEW_REPOSITORY';

export const USER_ACTIONS      = 'USER_ACTIONS';
export const USER_SERVICE      = 'USER_SERVICE';
export const USER_REPOSITORY   = 'USER_REPOSITORY';
export const USER_INFO_REDUCER = 'USER_INFO_REDUCER';

export const AGREEMENT_ACTIONS    = 'AGREEMENT_ACTIONS';
export const AGREEMENT_SERVICE    = 'AGREEMENT_SERVICE';
export const AGREEMENT_REPOSITORY = 'AGREEMENT_REPOSITORY';

export const AGREEMENT_NEW_CREATE_COMPONENT          = 'AGREEMENT_NEW_CREATE_COMPONENT';
export const AGREEMENT_EDIT_CONTAINER_COMPONENT      = 'AGREEMENT_EDIT_CONTAINER_COMPONENT';
export const AGREEMENT_EDIT_FORM_COMPONENT           = 'AGREEMENT_EDIT_FORM_COMPONENT';
export const AGREEMENT_LIST_CONTAINER_COMPONENT      = 'AGREEMENT_LIST_CONTAINER_COMPONENT';
export const AGREEMENT_LIST_ITEM_COMPONENT           = 'AGREEMENT_LIST_ITEM_COMPONENT';
export const AGREEMENT_LIST_COMPONENT                = 'AGREEMENT_LIST_COMPONENT';
export const AGREEMENT_DETAIL_CONTAINER_COMPONENT    = 'AGREEMENT_DETAIL_CONTAINER_COMPONENT';
export const AGREEMENT_DETAIL_GENERAL_INFO_COMPONENT = 'AGREEMENT_DETAIL_GENERAL_INFO_COMPONENT';
export const AGREEMENT_DETAIL_LENGTH_COMPONENT       = 'AGREEMENT_DETAIL_LENGTH_COMPONENT';
export const AGREEMENT_DETAIL_ARTIFACTS_COMPONENT    = 'AGREEMENT_DETAIL_ARTIFACTS_COMPONENT';

export const COUNTERPARTY_ACTIONS    = 'COUNTERPARTY_ACTIONS';
export const COUNTERPARTY_SERVICE    = 'COUNTERPARTY_SERVICE';
export const COUNTERPARTY_REPOSITORY = 'COUNTERPARTY_REPOSITORY';

export const ALERT_ACTIONS = 'ALERT_ACTIONS';

export const ALERT_LIST_COMPONENT      = 'ALERT_LIST_COMPONENT';
export const ALERT_LIST_ITEM_COMPONENT = 'ALERT_LIST_ITEM_COMPONENT';

export const AGREEMENT_TYPE_ACTIONS    = 'AGREEMENT_TYPE_ACTIONS';
export const AGREEMENT_TYPE_SERVICE    = 'AGREEMENT_TYPE_SERVICE';
export const AGREEMENT_TYPE_REPOSITORY = 'AGREEMENT_TYPE_REPOSITORY';

export const FILE_UPLOAD = 'FILE_UPLOAD';

export const RETRIEVAL_API_SERVICE = 'RETRIEVAL_API_SERVICE';

export const PERSISTENCE_API_SERVICE_URL = 'PERSISTENCE_API_SERVICE_URL';

export const DASHBOARD_COMPONENT = 'DASHBOARD_COMPONENT';

export const PROGRESS_BAR = 'PROGRESS_BAR';
